name: Feature Request
description: Propose a new feature for the Discord Bot Framework Kernel
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature. Please ensure it doesn't already exist in the current implementation.

  - type: dropdown
    id: feature-type
    attributes:
      label: Category
      description: Select the feature category
      options:
        - Bot Commands
        - Module Architecture
        - Security
        - Performance
        - Integration
        - Development Tools
        - User Experience
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem-description
    attributes:
      label: Problem Statement
      description: Describe the current limitation or challenge
      placeholder: |
        - Current limitation
        - Impact on users
        - Use case scenarios
    validations:
      required: true

  - type: textarea
    id: solution-description
    attributes:
      label: Proposed Solution
      description: Outline your solution approach
      placeholder: |
        - Implementation details
        - Expected behavior
        - Success criteria
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Approaches
      description: Describe alternative solutions considered
      placeholder: |
        - Alternative solutions
        - Trade-offs
        - Decision rationale

  - type: textarea
    id: implementation-details
    attributes:
      label: Technical Specification
      description: Provide implementation details
      placeholder: |
        - Dependencies
        - API changes
        - Integration points
        - Security considerations

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Indicate implementation priority
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      options:
        - label: I have verified this feature doesn't exist
          required: true
        - label: I have checked for duplicate requests
          required: true
        - label: I understand the review process
          required: true

  - type: textarea
    id: contribution
    attributes:
      label: Implementation Contribution
      description: Indicate your interest in contributing
      placeholder: |
        - Implementation capacity
        - Technical expertise
        - Time commitment 
